version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports: 
      - 80:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - php
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql:/var/lib/mysql
  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./:/var/www/html
  composer:
    build:
      context: .
      dockerfile: docker/composer.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
  npm:
    image: node:21.6.0-alpine
    volumes:
      - ./:/var/www/html
    entrypoint: ["npm"]
    working_dir: /var/www/html
  artisan:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/artisan"]